[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-nostartfiles",
]

[build]
target = "xtensa-esp32s3-none-elf"

[toolchain]
channel = "esp"

[unstable]
build-std = ["core", "alloc"]
